### ISSUE TITLE
MediaStream Deprecations

### ISSUE THREAD

**Issue by DoubangoTelecom** [DoubangoTelecom/sipml5#231]
https://groups.google.com/forum/#!topic/doubango/AItIvbSzc3Q
Chrome is going to deprecate three mediastream APIs in it next update in November. How does this affect the current sipml5 API. I can still see the use of deprecated APIs in latest sipml5. 

There are three MediaStream deprecations in Chrome 45:

MediaStream.ended
MediaStream.label
MediaStream.stop()
In parallel are two additions:

MediaStream.active
MediaStreamTrack.stop()
Source : https://developers.google.com/web/updates/2015/07/mediastream-deprecations?hl=en
What is the plan for sipml5 to implement these changes??

**Comment by bhakimi** [comment]
this is a big worry of mine too, we have tons of people that use sipml5 and may have issues after

**Comment by bhakimi** [comment]
are there any plans to address this or fix it?

**Comment by deltapath-eric** [comment]
Maybe you can try to reference this.

https://github.com/sipml5/sipml5/pull/3/files

Caution: this is just a search result from Google and I DO NOT test this before.

**Comment by bhakimi** [comment]
got this back.. i guess there is more code i need to implement?

Uncaught TypeError: this.o_local_stream.stop is not a function

**Comment by alepolidori** [comment]
> got this back.. i guess there is more code i need to implement?

> Uncaught TypeError: this.o_local_stream.stop is not a function

I guess that this depends on https://goo.gl/olv9Xu
