### ISSUE TITLE
getUserMedia() no longer works

### ISSUE THREAD

**Issue by AgustinOrd** [DoubangoTelecom/sipml5#234]
Hi, im new in this project and doing some test y found this :
"getUserMedia() no longer works on insecure origins. To use this feature, you should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details." 
on tmedia_session.jsep.js "svn 240"
Im using Chrome Versión 47.0.2526.73 m
There is any work arround to this ?
I´m goint to try with https but I have no experience with WSS in asterisk!!! 
best reagards

**Comment by DoubangoTelecom** [comment]
There is no workaround to this

**Comment by bhakimi** [comment]
What version of asterisk are you using ?
On Dec 4, 2015 6:31 AM, "AgustinOrd" <notifications@github.com> wrote:

> Hi, im new in this project and doing some test y found this :
> "getUserMedia() no longer works on insecure origins. To use this feature,
> you should consider switching your application to a secure origin, such as
> HTTPS. See https://goo.gl/rStTGz for more details."
> on tmedia_session.jsep.js "svn 240"
> Im using Chrome Versión 47.0.2526.73 m
> There is any work arround to this ?
> I´m goint to try with https but I have no experience with WSS in
> asterisk!!!
> best reagards
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/DoubangoTelecom/sipml5/issues/234>.
>

-- 


20950 Warner Center Lane, Building A | Woodland Hills | California | 91367
Phone: 888-456-5454 | *Fax:* 888-401-7809 
*Web:* www.safesoftsolutions.com

**Comment by AgustinOrd** [comment]
Asterisk 13
