### ISSUE TITLE
Remove Stream not yet implemented

### ISSUE THREAD

**Issue by IvanKalashnikov** [DoubangoTelecom/sipml5#240]
Cant call from firefox last version. I have this error, when i try to call from demo sipml5 https://www.doubango.org/sipml5
Error:
DOMException [NotSupportedError: "removeStream not yet implemented"
code: 9
nsresult: 0x80530009
location: https://www.doubango.org/sipml5/SIPml-api.js?svn=241:3]

Thank you

**Comment by DoubangoTelecom** [comment]
This function is called when you hangup the call and the exception is catched. You can safely ignore the message. The stream will be cleanly stopped using AudioTracks.stop()

**Comment by IvanKalashnikov** [comment]
>This function is called when you hangup the call and the exception is catched.
I get this error, when i try a call, not hung up.
