### ISSUE TITLE
sipml5 doesn't work in chrome 49

### ISSUE THREAD

**Issue by JinMinJeon** [DoubangoTelecom/sipml5#242]
Hello. i am working on sip client application with sip-ml5. it has been worked well.

but i got an error after installed Chrome version 49.

It always happens click to dial.

![2016-03-03 6 39 47](https://cloud.githubusercontent.com/assets/16235286/13490398/9fd7e88a-e16f-11e5-9229-b8a37e9538f2.png)

May i get some hint to solve this problem?

Thanks in advance.

**Comment by xandersytsevich** [comment]
Actual problem on production server!

**Comment by garronej** [comment]
+1

**Comment by Thisman** [comment]
same problem

**Comment by JinMinJeon** [comment]
Now it seems to be work. Thanks for your help.

**Comment by JulianPorras** [comment]
+1

**Comment by pablito25sp** [comment]
This should be closed. It's working ok since version 2.0.3.
