### ISSUE TITLE
/null call on call end (Media Removed)

### ISSUE THREAD

**Issue by Pauldic** [DoubangoTelecom/sipml5#244]
I have been seeing this bug specifically on Chrome v47/48/49 since svn 242/243/250, though I never worried about it cos it seems to be harmless. However, as our application continued to increase with more front end js, this appeared to be breaking our code thus need for elimination. We connect our WebRTC client to Asterisk using sipml5.

Each time a call between the RTC client and other clients is droped/ended/rejected there is always an unknown call to https://currentpage/null eg https://www.doubango.org/sipml5/null. I am not really sure why this is happening but I traced it to SIPml-api.js confirming that it happens when "Media Removed" event is fired. 

> case tsip_event_type_e.INVITE:
>     if (a.o_session.o_stack.on_event_invite) {
>         setTimeout(function() {
>             a.o_session.o_stack.on_event_invite(a)
>         }, 1)
>     }
> break;

The good news is that this is not required for our purpose thus my little work around:

> case tsip_event_type_e.INVITE:
>     if (a.o_session.o_stack.on_event_invite) {
>         setTimeout(function() {
>             if(a.i_code==806 && (a.e_invite_type==409 || a.e_invite_type==411)) return;
>             a.o_session.o_stack.on_event_invite(a)
>         }, 1)
>     }
> break;

I am sure this is not the best solution

**Comment by finethanks** [comment]
Same artifact

**Comment by DoubangoTelecom** [comment]
We're calling attachMediaStream(null), this was required in early WebRTC versions to release the camera. You can safely ignore the message
