### ISSUE TITLE
simpl5 won't stop ringing in firefox

### ISSUE THREAD

**Issue by magg** [DoubangoTelecom/sipml5#245]
I'm making a test call between two peers using the tutorial found at: https://kunjans.wordpress.com/2015/01/09/web-sip-client-sipml5-with-asterisk-13-on-centos-6-6/

I'm using firefox 44 to make the call, and chrome 49 to answer.... won't firefox 44 won't stop ringing after answering the call in chrome

note: i can't make the call from chrome because of error "Media stream permission denied
"

**Comment by DoubangoTelecom** [comment]
Chrome requires https://. Check the camera permission settings
