### ISSUE TITLE
The function  `attachMediaStream` URL.createObjectURL(b): not work on latest version of Chrome

### ISSUE THREAD

**Issue by JulianPorras** [DoubangoTelecom/sipml5#246]
**This message appear:**
When I will start to working.

> Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

**Comment by 62mkv** [comment]
+1 having the same issue with Chrome 49

**Comment by 62mkv** [comment]
apparently occurs when trying to createObjectURL from null. o_remote_stream is null, for some reasons. Have to look at it further tomorrow

**Comment by DoubangoTelecom** [comment]
This issue was fixed weeks ago: https://github.com/DoubangoTelecom/sipml5/issues/242

**Comment by DoubangoTelecom** [comment]
This issue was fixed weeks ago: https://github.com/DoubangoTelecom/sipml5/issues/242

**Comment by DoubangoTelecom** [comment]
This issue was fixed weeks ago: https://github.com/DoubangoTelecom/sipml5/issues/242

**Comment by DoubangoTelecom** [comment]
This issue was fixed weeks ago: https://github.com/DoubangoTelecom/sipml5/issues/242

**Comment by DoubangoTelecom** [comment]
This issue was fixed weeks ago: https://github.com/DoubangoTelecom/sipml5/issues/242
