### ISSUE TITLE
DTLS handshake - Audio delay

### ISSUE THREAD

**Issue by sergioooo** [DoubangoTelecom/sipml5#247]
Hi,

I've got an interesting issue with incoming calls, the longer you wait to answer, the longer it takes for sound to start flowing.

I've narrowed down the issue to the DTLS handshake between Chrome and Asterisk.
Chrome is sending DTLS Client Hello, but Asterisk responds only after it receives SIP/2.0 200 OK from sipml5.
Chrome is sending the DTLS Client Hello in incrementing intervals, each 1,2,4,8... seconds.
Otherwise calls work perfectly.

Is this an issue with Asterisk or sipml5, and how to resolve it?

Would it make more sense to delay the Chrome initiating handshake until we answer i.e. send 200 OK, or "fix" asterisk to answer to the DTLS Client Hello?

Following line seems to initiate the Chrome DTLS Client Hello
```
this.o_pc = new window.RTCPeerConnection(
```

When I run the client via Electron/0.37.2, I get the following errors:
```
ERROR:dtlstransportchannel.cc(489)] Jingle:Channel[audio|1|__]: Received non-DTLS packet before DTLS complete.
```
This error will keep repeating until asterisk responds with DTLS Server Hello and certificate...after that sound starts flowing.

Here is the wireshark dump of dtls http://imgur.com/vbAbuSk arrow points to the point where sound starts flowing.
Note the Chrome sending DTLS Client Hello in incrementing intervals each 1,2,4 then at last 8 seconds.

Configuration
```
sipml5 latest master https://github.com/DoubangoTelecom/sipml5/commit/e3152e1edf116b651de379b3cc971bf699787c26
Chrome/49.0.2623.87 on Windows 8.1 64x
CentOS Linux release 7.2.1511 (Core)
Asterisk 13.7.2 with the following patch https://issues.asterisk.org/jira/browse/ASTERISK-25265

sip.conf
--------
transport=udp,wss
encryption=yes
avpf=yes
savpf=yes
force_avp=yes
icesupport=yes
dtlsenable = yes
dtlsverify = no
dtlscertfile = ...
dtlsprivatekey = ...
dtlscipher = ALL
dtlssetup = actpass
dtlsfingerprint = sha-256

rtp.conf
--------
icesupport=true
stunaddr=stun.l.google.com:19302
```

[call.txt](https://github.com/DoubangoTelecom/sipml5/files/177099/call.txt)

**Comment by sergioooo** [comment]
Works perfectly with PJSIP on Asterisk.

**Comment by roginvs** [comment]
We have the same problem on Asterisk 11.21.0 - there is a delay in media in Chrome on incoming calls. A big delay can be noticed if call is answered after 8 seconds of ringing.
