### ISSUE TITLE
sipml5 doesn't work in firefox 47

### ISSUE THREAD

**Issue by gorbatenkov** [DoubangoTelecom/sipml5#264]
Hello, I am working on sip client application with sip-ml5 and it has been worked well,

but now i got few errors after installed Firefox version 47.

![screenshot_1](https://cloud.githubusercontent.com/assets/7262130/16110426/56b76a1a-33b6-11e6-9113-19725c8def34.png)
Mandatory/optional in createOffer options no longer works! Use {"offerToReceiveAudio":true,"offerToReceiveVideo":false,"mozDontOfferDataChannel":true} instead (note the case difference)!
NotSupportedError: removeStream not yet implemented...

May i get some hint to solve this problem?

Thanks in advance.

**Comment by benjaminW78** [comment]
Hello, same here for me as i try to hold the line i got the removestream exception and cannot get back the sound.

work perfectly well on google chrome but not in firefox 47

**Comment by gorbatenkov** [comment]
No luck with firefox 48 too
Anyone have solution?

**Comment by scottzhang** [comment]
firefox 49 not working. Neither was working for latest chrome. 
Basically I have not seen any working show.

**Comment by TaylorHawkes** [comment]
I'm having this same issue with Firefox 49 over https.  If someone wants to point me in the right direction I can take a look at resolving this issue....? 
 
Would be really good to get this working.
