### ISSUE TITLE
SIPML5 firefox taking more time for ICEGathering

### ISSUE THREAD

**Issue by varghesepaul** [DoubangoTelecom/sipml5#268]
Hello Team,

We are noticing more time for ICEgathering in Firefox. But it works well in Chrome.

FireFox Version : 46.0 

Console Log:

![sipml5](https://cloud.githubusercontent.com/assets/6231422/17727994/7037ecf4-647a-11e6-8091-82d07fd34e00.png)

12:58:16.251 ICE servers:[{"url":"stun:23.21.150.121:3478"},{"url":"stun:216.93.246.18:3478"},{"url":"stun:66.228.45.110:3478"},{"url":"stun:173.194.78.127:19302"}]

**12:58:17.591** onIceCandidate = gathering 

**12:58:29.090** onIceCandidate = complete 

From the above console log we can see it is taking 12 seconds for ICE gathering.

URL used for testing : https://www.doubango.org/sipml5/call.htm?svn=250# 

Any thoughts will be appreciated on this. 

 Regards

Varghese Paul

**Comment by roginvs** [comment]
Hi! Can you test [this](https://github.com/roginvs/sipml5/blob/master/release/SIPml-api.js) version? I am not sure is it your issue, but probably [this](https://github.com/roginvs/sipml5/commit/a1fae10b5b52460f4cb5fd14315bfe24cd22cd57) patch will help

**Comment by varghesepaul** [comment]
Hi @roginvs ,

Thanks for the reply. I will test and let you know the result shortly. 

Regards

Varghese Paul

**Comment by varghesepaul** [comment]
Hello Guys,

The issues was resolved. It was a connectivity issue with ICE Server.

Closing the ticket.

Regards

Varghese Paul
