### ISSUE TITLE
Is this project not supported any more?

### ISSUE THREAD

**Issue by blackc2004** [DoubangoTelecom/sipml5#283]
Is this project not being developed or supported any more? It seems like it's not been updated in a long time.

**Comment by DoubangoTelecom** [comment]
The last commit is Feb 2017.

**Comment by blackc2004** [comment]
That doesn't really answer my question. bootstrap hasn't been updated in ages and uses an unsupported version, one file was updated this month, there were two commits during 2015. I'm assuming this means it's not being supported any more or updated.
