### ISSUE TITLE
How to modify the User-Agent?

### ISSUE THREAD

**Issue by knightjie99** [DoubangoTelecom/sipml5#317]
My Project need to modify the User-Agent. I tried ,but failed.

**Comment by mosea3** [comment]
in /Call.html@Line [396](https://github.com/DoubangoTelecom/sipml5/blob/master/call.htm#L396),
you can modify User-Agent in SIP-Headers to match your needs:
`sip_headers: [
                            { name: 'User-Agent', value: 'IM-client/OMA1.0 sipML5-v1.2016.03.04' },
                            { name: 'Organization', value: 'Doubango Telecom' }
                    ]`
