### ISSUE TITLE
exist the autoanswer?

### ISSUE THREAD

**Issue by jesusQuintana-30-2017** [DoubangoTelecom/sipml5#332]
i need the autoanwer for operation un callcenter the agent are "peresosos"

**Comment by davidandradeb** [comment]
Hola Jesus como estas, mira en tu archivo de implementacion puedes buscar el metodo onSipEventStack ahi entras en un case case 'i_new_call' realizas el auto-answer, esta seria la implementacion para tu codigo:

`function onSipEventStack(e ) {
switch (e.type) {

case 'i_new_call':
        {
                if (oSipSessionCall) {
                                e.newSession.hangup(); // comment this line for multi-line support
                }else{
                                oSipSessionCall = e.newSession;
                                oSipSessionCall.setConfiguration(oConfigCall);
                               var sRemoteNumber = (oSipSessionCall.getRemoteFriendlyName() || 'unknown');
                               oSipSessionCall.accept(oConfigCall); // en esta linea abres la linea y contestas la llamada.
                }
        }
}
}`

Si necesitas mas detalles de la implementacion me avisas, pero en terminos generales yo lo tengo asi como te lo puse aca y funciona muy bien en un ambiente de produccion, obviamente puedes ir mas alla y agregar en tu plan de marcacion un header que te indique si se debe autocontestar o no y dependiendo de eso disparas el accept.

Felicidades y exito en tu implementacion

**Comment by jesusQuintana-30-2017** [comment]
gracias David ya resolví el tema gracias por tu ayuda.

**Comment by mosea3** [comment]
David, youre a real MVP here 😁
Thanks, I was thinking about this auto-respond too. 

Regards

Andy Moser

Von meinem Smartphone gesendet
