### ISSUE TITLE
Failed to get local SDP offer

### ISSUE THREAD

**Issue by GoogleCodeExporter** [DoubangoTelecom/sipml5#56]
```
hello,
i'm using ubuntu / chrome 23

i'm using the live demo. 

When i receive a call from a phone i get an arror : Failed to get local SDP 
offer.
i'm attaching the error from the console.

thank you for any help.

```

Original issue reported on code.google.com by `jaballah...@gmail.com` on 13 Nov 2012 at 1:51

Attachments:
- [error demo ](https://storage.googleapis.com/google-code-attachments/sipml5/issue-56/comment-0/error demo)

**Comment by Pauldic** [comment]
Thanks @CraigShe your suggestion solved my 3 weeks of night mere atlest on Chrome Version 48.0.2564.97 (64-bit), Asterisk 13.7 using PJSIP I can make in/out bound calls. However, I could not call out nor receive incoming calls from Mozilla.

I am happy I have atleast one browser fully functional expect for Video calls which not much a big deal for now.
